# ===== App =====
app.mappingsDir=/opt/normal-sync/mappings
app.enableIdempotency=true

# ===== Kafka =====
spring.kafka.bootstrap-servers=10.219.2.82:9092
spring.kafka.consumer.group-id=meraki-normal-sync-v1
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.max-poll-records=200
spring.kafka.listener.ack-mode=manual

# Topics you want to consume (comma-separated)
kafka.topics=T24.FBNK_CUSTOMER
kafka.dlqSuffix=.DLQ

# ===== Oracle (KNOBS DB) =====
spring.datasource.url=jdbc:oracle:thin:@//172.16.123.69:1521/KNOB12
spring.datasource.username=nobsdb
spring.datasource.password=nobsdb
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

# ===== Logging =====
logging.level.root=INFO
logging.level.org.apache.kafka=INFO