# ===== App =====
app.mappingsDir=E:/Programs/meraki-normal-sync/mappings
app.enableIdempotency=true

# -------------------------
# Kafka topics you want to consume (comma-separated)
# -------------------------
kafka.topics=T24.FBNK_CUSTOMER
kafka.dlqSuffix=.DLQ

# -------------------------
# Camel Kafka Component
# -------------------------
camel.component.kafka.brokers=10.219.2.82:9092
camel.component.kafka.groupId=meraki-normal-sync-v1
camel.component.kafka.autoOffsetReset=earliest
camel.component.kafka.maxPollRecords=200
camel.component.kafka.consumersCount=1

# Camel startup logs
camel.springboot.main-run-controller=true

# ===== Oracle (KNOBS DB) =====
spring.datasource.url=jdbc:oracle:thin:@172.16.123.69:1521:KNOB12
spring.datasource.username=nobsdb
spring.datasource.password=nobsdb
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.initialization-fail-timeout=10000

logging.level.com.zaxxer.hikari=INFO
logging.level.org.springframework.jdbc=INFO

# ===== Logging =====
logging.level.root=INFO
logging.level.org.apache.kafka=INFO

management.server.port=9090

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always